version: 1.0.{build}

platform:
  - x86
  - x64

environment:
  global:
    APPVEYOR_OS_NAME: windows
    CHERE_INVOKING: 1
    MSYS2_PATH: c:\msys64
    #CCACHE settings : Appveyor cache is limited to 1G so we limit CCACHE to 2G and expect 50% compression...
    CCACHE_DIR: "%APPVEYOR_BUILD_FOLDER%\\.ccache"
    CCACHE_MAXSIZE: 2G
  matrix:
  #MSYS2 Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILDER: MSYS2
  #VisualStudio Building
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      BUILDER : VS

configuration: Debug
shallow_clone: true
clone_depth: 10


init:
# fix for https://github.com/appveyor/ci/issues/2571
- del C:\Windows\System32\libssl-*.dll C:\Windows\system32\libcrypto-*.dll
- del C:\Windows\SysWOW64\libssl-*.dll C:\Windows\SysWOW64\libcrypto-*.dll



for:
  -
    matrix:
      only:
        - BUILDER: MSYS2
    
    cache:
    - .ccache

    install:
      - |-
        set MSYSTEM=%platform:86=32%
        set MSYSTEM=%MSYSTEM:x=MINGW%
        cd C:\
        ren msys64 msys64_old
        C:\msys64_old\usr\bin\bash -lc "curl -L http://repo.msys2.org/distrib/msys2-x86_64-latest.tar.xz | xz -d | tar -xf -"
        %MSYS2_PATH%\usr\bin\bash -lc "pacman --noconfirm -Syu"
        %MSYS2_PATH%\usr\bin\pacman --noconfirm -S --needed unzip rsync wget libopenssl
        cd "%APPVEYOR_BUILD_FOLDER%"
        %MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/msys2/install.sh"
        %MSYS2_PATH%\usr\bin\bash -lc "echo $PATH"

    before_build:
      - |-
        %MSYS2_PATH%\usr\bin\bash -lc "ccache -z"
        %MSYS2_PATH%\usr\bin\bash -lc "ccache -s"

    build_script:
      - '%MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/msys2/build.sh"'

    test_script:
      - '%MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/msys2/run_tests.sh"'

    after_test:
      - '%MSYS2_PATH%\usr\bin\bash -lc "ccache -s"'


  -
    matrix:
      only:
        - BUILDER: VS

    install:
      - |-
        set BITS=%platform:86=32%
        set BITS=%BITS:x=%
        %MSYS2_PATH%\usr\bin\pacman --noconfirm -S --needed unzip rsync wget libopenssl
        set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin;%PATH%
        %MSYS2_PATH%\usr\bin\bash -lc "scripts/ci/vs/install.sh"

    build_script:
      - |-
          echo BITS=%BITS%
          msbuild libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj  /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
          msbuild examples/templates/emptyExample/emptyExample.vcxproj  /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
          msbuild examples/templates/allAddonsExample/allAddonsExample.vcxproj  /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    test_script:
      - |-
        cd scripts/ci/vs
        .\run_tests.bat
