name: build-vs

on:
  push:
    paths-ignore:
    - '**/*.md'
    #- 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
    
jobs:

  build-vs2019:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - platform: x64
            bits: 64
    defaults:
      run:
        shell: msys2 {0}
    env: 
      BITS: ${{ matrix.bits }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            unzip
            rsync
            wget
      - name: Install dependencies
        run:
          ./scripts/ci/vs/install.sh
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
      #- name: Build
      #  working-directory: ${{env.GITHUB_WORKSPACE}}
      #  run:
      #    msbuild libs/openFrameworksCompiled/project/vs/openframeworksLib.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }}
      #- name: Build emptyExample
      #  working-directory: ${{env.GITHUB_WORKSPACE}}
      #  run:
      #    msbuild examples/templates/emptyExample/emptyExample.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }}
      - name: Build allAddonsExample
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run:
          msbuild examples/templates/allAddonsExample/allAddonsExample.vcxproj /p:configuration=release /p:platform=${{ matrix.platform }}
