name: build-linux64-and-arm

on:
  push:
    paths-ignore:
    - '**/*.md'
  pull_request:
    paths-ignore:
    - '**/*.md'
    
jobs:

  build-linux-platforms:
    runs-on: ubuntu-18.04
    strategy:
        matrix:
          cfg:
          - {target: linux64, libs: 64gcc6}
          - {target: linuxarmv6l, libs: armv6l}
          - {target: linuxarmv7l, libs: armv7l}
    env:
     TARGET: ${{matrix.cfg.target}}
    steps:
    - uses: actions/checkout@v2
    - name: Download libs
      run: ./scripts/linux/download_libs.sh -a ${{matrix.cfg.libs}};
    - name: Install dependencies
      run: ./scripts/ci/$TARGET/install.sh;
#    - name: Install gcc4
#      run: if [ ${{matrix.cfg.target}} = "64gcc4" ]; then
#                sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
#                sudo apt-get update -q;
#                sudo apt-get install gcc-4.9 g++-4.9;
#            fi
    - name: Build
      run: if [ "$TARGET" = "linux64" ]; then
            scripts/ci/$TARGET/build.sh;
            scripts/ci/$TARGET/run_tests.sh;
           else
            scripts/ci/$TARGET/build.sh;
           fi
    - name: Upload Libs
      run: scripts/ci/upload_of_lib.sh;
      env:
        GA_CI_SECRET: ${{ secrets.CI_SECRET }}

